## K Nearest Neighbour Algorithm

In [14]:
import numpy as np 
import pandas as pd 
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [15]:
# load the dataset
data = pd.read_csv("car.data")
print(data.head())

  buying  maint doors person lug_boot safety  class
0  vhigh  vhigh     2      2    small    low  unacc
1  vhigh  vhigh     2      2    small    med  unacc
2  vhigh  vhigh     2      2    small   high  unacc
3  vhigh  vhigh     2      2      med    low  unacc
4  vhigh  vhigh     2      2      med    med  unacc


In [16]:
X = data[['buying', 'maint', 'safety']].values
y = data[['class']]

print(X, y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [ ]:
# convert the data into numerical values
# shape[0] = number of rows
# shape[1] = number of columns

Le = LabelEncoder()
# loop over the values of each column and transform  - for pandas to convert all rows
# for i in range(X.shape[1]): 
#     X.iloc[: , i] = Le.fit_transform(X.iloc[:, i])

# numpy style to convert into array
for i in range(len(X[0])): 
    X[: ,i] = Le.fit_transform(X[:, i])
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [18]:
# converting y values

label_mapping = { 
    'unacc' : 0, 
    'acc' : 1, 
    'good': 2, 
    'vgood' : 3, 
}

y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


/var/folders/h6/2zxlvljx3vb0hvfr9zhz6trh0000gn/T/ipykernel_25484/3806536676.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


In [38]:
# Create the model 

knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights = 'uniform')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

knn.fit(X_train, y_train)

prediction = knn.predict(X_test)

accuracy = metrics.accuracy_score(y_test, prediction)
print('predictions: ', prediction)
print('accuracy: ', accuracy)

predictions:  [0 0 2 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 0 0
 0 0 1 0 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 2 0 0 1 0 0 1 1 0
 0 1 0 1 1 0 0 0 1 0 1 0 2 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 0 1 0 1 2 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 2 0 0 0 0 1 1 0 0 0 0
 1 2 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0
 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 2 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 0 0 0]
accuracy:  0.7601156069364162


/Users/deepak/Desktop/Python/.cortex_engine/lib/python3.13/site-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [43]:
# printing the values 

a = 1727
print("actual values: ", y[a])
print("predicted value: ", knn.predict(X)[a])

actual values:  [3]
predicted value:  0
